_target_: proconsul.train.prompt_strategy.BasePromptStrategy
_convert_: "all"

instruction: |
  [INST] <<SYS>>
  Write a docstring for the following C++ code.
  You should write the shortest possible docstring.
  <</SYS>>

  {code} [/INST]
